### ISSUE TITLE
OSL Workshop - Preprocessing

### ISSUE THREAD

**Issue by matsvanes** [OHBA-analysis/osl#186]
Please leave your feedback here

**Comment by Kohliver** [comment]
**1_manual_preprocessing:**

1. At end of first text block "TO DO:" can probably be removed.
2. In cell 7 (bandpass filtering and plotting of data) two many subplots are created. 

```python
psd = raw.compute_psd(picks='meg')
fig, ax = plt.subplots(2,**3**, figsize = (10,6))
psd.plot(axes=ax[:,0])
ax[0,0].set_title('Raw data \n Gradiometers (204 channels)')

raw_bp = raw.copy().filter(l_freq=0.25, h_freq=100)
psd_bp = raw_bp.compute_psd(picks='meg')

psd_bp.plot(axes=ax[:,1])
ax[0,1].set_title('After band-pass (BP) filter \n Gradiometers (204 channels)')
``` 

4. Code Cell 8: I am not sure if I understand title of plot on the left ('The signal drift to increasing \n amplitude before band-pass filtering').

5. Code Cell 9: Description of what is happening as comment above code instead of in a text cell above. Is this on purpose? 
Also I think it might be nice to highlight here that mne functions alter the raw object even if it is assigned to another variable (I think). If this is not correct never mind.

6. Code Cell 9 gives error because no axis and figure are created before running:

```python
 psd_notch.plot(axes=ax[:,2]) # See the plot above
 ```
7.	It is mentioned that ica.apply() removes the labeled components, but I think it might be worth to make explicit that if this is not done, the marked components won’t be removed. (I did this mistake more than once.)


I hope this is helpful :)

**Comment by Kohliver** [comment]
**2_automatic_preprocessing:**

1. Text Cell after code cell in which config is specified: an **after** is missing in
“Note that any preprocessing steps that come after ICA (e.g., epoching) would then also come this manual step.”

2. In Text Cell after code cell calling help(run_proc_chain):
**Is** instead of **if** in: 
outdir: By default the preprocessed data is not saved. Add a path here **is** you wish to save it.

3. In first text cell is still a TO DO point.

**Comment by yingjoeyzhou** [comment]
> Yes sort of. In general, I found the instructions on unzipping the data missing from the tutorial.

and it took me a while to figure out how to download stuff from OSF.

**Comment by yingjoeyzhou** [comment]
i have an extremely naive question re the jupyter notebook. i read the link you put in there, but it was unclear (maybe only to me) if i have to download *everything* on OSF to get jupyter notebook running. moreover, it is unclear if, to get jupyter notebook running, i need to have the stuff downloaded from OSF nested under the `osl` folder.

**Comment by ricsinaruto** [comment]
**1_manual_preprocessing:**

1. code cell 14: it is mentioned that segments and channels can be removed manually, however there is no mention of how to save this to the raw object? Also, I haven't been able to "drag a window over a time period"
2. code cell 19: I don't know if it's just me but clicking stuff in the interactive plot is extremely slow. maybe have a warning for this? also running this cell created dozens of empty figures below the ICA figure for some reason.


**2_automatic_preprocessing:**

1. None of the IFrame codes work for me, nothing appears when I run it in the notebook.

**Comment by ricsinaruto** [comment]
> > i have an extremely naive question re the jupyter notebook. i read the link you put in there, but it was unclear (maybe only to me) if i have to download _everything_ on OSF to get jupyter notebook running. moreover, it is unclear if, to get jupyter notebook running, i need to have the stuff downloaded from OSF nested under the `osl` folder.
> 
> to make it more concrete, when i ran `2_automatic_preprocessing`, i got an error (see screenshot) <img alt="Screenshot 2023-03-30 at 16 13 35" width="1065" src="https://user-images.githubusercontent.com/31690290/228773130-36458fb6-5e3f-48a1-b094-c61352b2c855.png">
> 
> and here's my folder structure: <img alt="Screenshot 2023-03-30 at 16 14 51" width="491" src="https://user-images.githubusercontent.com/31690290/228773326-2266b881-4a00-44d4-b996-5596e7eadc17.png">

I think the fif files should be under data folder, so maybe move them one folder up.

**Comment by matsvanes** [comment]
> > > i have an extremely naive question re the jupyter notebook. i read the link you put in there, but it was unclear (maybe only to me) if i have to download _everything_ on OSF to get jupyter notebook running. moreover, it is unclear if, to get jupyter notebook running, i need to have the stuff downloaded from OSF nested under the `osl` folder.
> > 
> > 
> > to make it more concrete, when i ran `2_automatic_preprocessing`, i got an error (see screenshot) <img alt="Screenshot 2023-03-30 at 16 13 35" width="1065" src="https://user-images.githubusercontent.com/31690290/228773130-36458fb6-5e3f-48a1-b094-c61352b2c855.png">
> > and here's my folder structure: <img alt="Screenshot 2023-03-30 at 16 14 51" width="491" src="https://user-images.githubusercontent.com/31690290/228773326-2266b881-4a00-44d4-b996-5596e7eadc17.png">
> 
> I think the fif files should be under data folder, so maybe move them one folder up.

Yes @ricsinaruto that's correct. The .fif files should directly be in the `data` folder (not the `data1-3` folder). 
From my experience, it seems like Jupyter Notebook can only see files in a lower directory from where you opened the notebook. E.g. when in the terminal, you
```
cd ~
jupyter notebook
```
it can read files in `~/...`, but if you
```
cd ~/osl/workshop/preprocessing/data
jupyter notebook
```
your notebook won't be able to find files in `~/Documents`.

**Comment by Kohliver** [comment]
**2_automatic_preprocessing:**

1.	First Text Cell: “TO DO!” can probably be deleted.
2.	Code Cell 4: “TO DO” comment can probably be deleted.

**Comment by Kohliver** [comment]
> **1_manual_preprocessing:**
> 
> 1. code cell 14: it is mentioned that segments and channels can be removed manually, however there is no mention of how to save this to the raw object? Also, I haven't been able to "drag a window over a time period"
> 2. code cell 19: I don't know if it's just me but clicking stuff in the interactive plot is extremely slow. maybe have a warning for this? also running this cell created dozens of empty figures below the ICA figure for some reason.
> 
> **2_automatic_preprocessing:**
> 
> 1. None of the IFrame codes work for me, nothing appears when I run it in the notebook.


The Iframe codes work for me - not sure why. Maybe different browsers (or versions)?
